name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build archive
        run: |
          mkdir -p ./archive
          cp -a ./orca/. ./archive/
          cp ./guidepup.ini ./archive/
          cp ./LICENSE ./archive/

          tar -czf "./guidepup-orca-${{ github.event.release.tag_name }}.tar.gz" \
            -C ./archive .

      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            "${{ github.event.release.tag_name }}" \
            "guidepup-orca-${{ github.event.release.tag_name }}.tar.gz" \
            --clobber
